Switch to GitHub actions
packethost/cacher pull request #20
Opened 2021-07-15 16:27 UTC by nshalman

2021-07-15 17:09 UTC, mmlb requested changes

2021-07-15 17:09 UTC, mmlb commented on Makefile
>  endif
lets get rid of this whole section too

2021-07-15 17:22 UTC, nshalman commented on Makefile
>  endif
cleaned up.

2021-07-15 17:23 UTC, mmlb approved these changes

2021-07-15 17:24 UTC, mmlb commented
you should delete the `.drone.yaml` file too

2021-07-15 18:07 UTC, nshalman commented
> you should delete the `.drone.yaml` file too

Presumably that broke the drone runs. 🙃

2021-07-15 19:16 UTC, mmlb commented
> > you should delete the `.drone.yaml` file too
> 
> Presumably that broke the drone runs. upside_down_face

Yep, since this PR is titled `Switch to GitHub actions` that implies no more drone right? :D. Do we want to do it in 2 phases? Add GHA, ensure both work, remove drone?

2021-07-15 19:55 UTC, nshalman commented
> Yep, since this PR is titled `Switch to GitHub actions` that implies no more drone right? :D. Do we want to do it in 2 phases? Add GHA, ensure both work, remove drone?

Renamed to "Enable GitHub actions"

2021-07-19 18:51 UTC, matoszz approved these changes
I think we should work towards standardizing around some of the actions we use given nearly all our pipelines are identical, otherwise LGTM

2021-07-19 18:54 UTC, merged